// <auto-generated />
using System;
using DataAccess.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ECContext))]
    partial class ECContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.Concrete.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImageUrl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserTypeId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Booklet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ExamId");

                    b.HasIndex("GradeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ModifyUserId");

                    b.HasIndex("VariantId");

                    b.ToTable("Booklets");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CombineEntities.CompanyUser", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CombineEntities.QuestionAttahment", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("QuestionAttahments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BlockedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPenal")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PersentOfFine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ExamParameterId");

                    b.HasIndex("GradeId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ExamParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("ExamParameters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ExceptionalEntities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ForRoles.CombineRoleUrl", b =>
                {
                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleUrlId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppRoleId", "RoleUrlId");

                    b.HasIndex("RoleUrlId");

                    b.ToTable("CombineRoleUrls");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ForRoles.RoleUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleUrls");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PaymentSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("PaymentSummary");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuestionLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TextId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("GradeId");

                    b.HasIndex("ModifyUserId");

                    b.HasIndex("QuestionLevelId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TextId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("QuestionLevels");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("EndQuestionNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartQuestionNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubjectParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SubjectParameterId");

                    b.ToTable("QuestionParameters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShowAnswer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ResponseCount")
                        .HasColumnType("float");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AmountForQuestion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubjectParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SubjectId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ExamParameterId");

                    b.HasIndex("ModifyUserId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectParameters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SysException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SysExceptions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Text", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatUserId");

                    b.HasIndex("ModifyUserId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.AcademicYear", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("AcademicYears")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("AcademicYearsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppUser", b =>
                {
                    b.HasOne("EntityLayer.Concrete.UserType", "UserType")
                        .WithMany("AppUsers")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Attachment", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Attachments")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("AttachmentsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Booklet", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AcademicYear", "AcademicYear")
                        .WithMany("Booklets")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Booklets")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.Exam", "Exam")
                        .WithMany("Booklets")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Grade", "Grade")
                        .WithMany("Booklets")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Group", "Group")
                        .WithMany("Booklets")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("BookletsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.Variant", "Variant")
                        .WithMany("Booklets")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("CreatUser");

                    b.Navigation("Exam");

                    b.Navigation("Grade");

                    b.Navigation("Group");

                    b.Navigation("ModifyUser");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CombineEntities.CompanyUser", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "AppUser")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CombineEntities.QuestionAttahment", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Attachment", "Attachment")
                        .WithMany("QuestionAttahments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Question", "Question")
                        .WithMany("QuestionAttahments")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Exam", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Exams")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.ExamParameter", "ExamParameter")
                        .WithMany("Exams")
                        .HasForeignKey("ExamParameterId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Grade", "Grade")
                        .WithMany("Exams")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("ExamsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ExamParameter");

                    b.Navigation("Grade");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ExamParameter", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("ExamParameters")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("ExamParametersM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ExceptionalEntities.Payment", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Company", "Company")
                        .WithMany("Payments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ForRoles.CombineRoleUrl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppRole", "AppRole")
                        .WithMany("CombineRoleUrls")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ForRoles.RoleUrl", "RoleUrl")
                        .WithMany("CombineRoleUrls")
                        .HasForeignKey("RoleUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("RoleUrl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Grade", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Grades")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("GradesM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Group", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Groups")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("GroupsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PaymentSummary", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Company", "Company")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("EntityLayer.Concrete.PaymentSummary", "CompanyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Question", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AcademicYear", "AcademicYear")
                        .WithMany("Questions")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Questions")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.Grade", "Grade")
                        .WithMany("Questions")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("QuestionsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.QuestionLevel", "QuestionLevel")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionLevelId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Section", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Text", "Text")
                        .WithMany("Questions")
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("CreatUser");

                    b.Navigation("Grade");

                    b.Navigation("ModifyUser");

                    b.Navigation("QuestionLevel");

                    b.Navigation("QuestionType");

                    b.Navigation("Section");

                    b.Navigation("Subject");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionLevel", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("QuestionLevels")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("QuestionLevelsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionParameter", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("QuestionParameters")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("QuestionParametersM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.QuestionType", "QuestionType")
                        .WithMany("QuestionParameters")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.SubjectParameter", "SubjectParameter")
                        .WithMany("QuestionParameters")
                        .HasForeignKey("SubjectParameterId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");

                    b.Navigation("QuestionType");

                    b.Navigation("SubjectParameter");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionType", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("QuestionTypes")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("QuestionTypesM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Response", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AcademicYear", "AcademicYear")
                        .WithMany("Responses")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Responses")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("ResponsesM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.QuestionType", "QuestionType")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Subject", "Subject")
                        .WithMany("Responses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");

                    b.Navigation("Question");

                    b.Navigation("QuestionType");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Section", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Sections")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("SectionsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.Subject", "Subject")
                        .WithMany("Sections")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Subject", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Subjects")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("SubjectsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubjectParameter", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("SubjectParameters")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.ExamParameter", "ExamParameter")
                        .WithMany("SubjectParameters")
                        .HasForeignKey("ExamParameterId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("SubjectParametersM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.Subject", "Subject")
                        .WithMany("SubjectParameters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CreatUser");

                    b.Navigation("ExamParameter");

                    b.Navigation("ModifyUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Text", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Texts")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("TextsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Variant", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", "CreatUser")
                        .WithMany("Variants")
                        .HasForeignKey("CreatUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("EntityLayer.Concrete.AppUser", "ModifyUser")
                        .WithMany("VariantsM")
                        .HasForeignKey("ModifyUserId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CreatUser");

                    b.Navigation("ModifyUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Concrete.AcademicYear", b =>
                {
                    b.Navigation("Booklets");

                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppRole", b =>
                {
                    b.Navigation("CombineRoleUrls");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppUser", b =>
                {
                    b.Navigation("AcademicYears");

                    b.Navigation("AcademicYearsM");

                    b.Navigation("Attachments");

                    b.Navigation("AttachmentsM");

                    b.Navigation("Booklets");

                    b.Navigation("BookletsM");

                    b.Navigation("CompanyUsers");

                    b.Navigation("ExamParameters");

                    b.Navigation("ExamParametersM");

                    b.Navigation("Exams");

                    b.Navigation("ExamsM");

                    b.Navigation("Grades");

                    b.Navigation("GradesM");

                    b.Navigation("Groups");

                    b.Navigation("GroupsM");

                    b.Navigation("QuestionLevels");

                    b.Navigation("QuestionLevelsM");

                    b.Navigation("QuestionParameters");

                    b.Navigation("QuestionParametersM");

                    b.Navigation("QuestionTypes");

                    b.Navigation("QuestionTypesM");

                    b.Navigation("Questions");

                    b.Navigation("QuestionsM");

                    b.Navigation("Responses");

                    b.Navigation("ResponsesM");

                    b.Navigation("Sections");

                    b.Navigation("SectionsM");

                    b.Navigation("SubjectParameters");

                    b.Navigation("SubjectParametersM");

                    b.Navigation("Subjects");

                    b.Navigation("SubjectsM");

                    b.Navigation("Texts");

                    b.Navigation("TextsM");

                    b.Navigation("Variants");

                    b.Navigation("VariantsM");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Attachment", b =>
                {
                    b.Navigation("QuestionAttahments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Company", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("PaymentSummary");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Exam", b =>
                {
                    b.Navigation("Booklets");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ExamParameter", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("SubjectParameters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ForRoles.RoleUrl", b =>
                {
                    b.Navigation("CombineRoleUrls");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Grade", b =>
                {
                    b.Navigation("Booklets");

                    b.Navigation("Exams");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Group", b =>
                {
                    b.Navigation("Booklets");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Question", b =>
                {
                    b.Navigation("QuestionAttahments");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionLevel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.QuestionType", b =>
                {
                    b.Navigation("QuestionParameters");

                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Section", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Subject", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");

                    b.Navigation("Sections");

                    b.Navigation("SubjectParameters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubjectParameter", b =>
                {
                    b.Navigation("QuestionParameters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Text", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UserType", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Variant", b =>
                {
                    b.Navigation("Booklets");
                });
#pragma warning restore 612, 618
        }
    }
}
