//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLayer.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreLayer.Constants.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tədris ili.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş tədris ili.
        /// </summary>
        public static string AcademicYearId {
            get {
                return ResourceManager.GetString("AcademicYearId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual qiyməti.
        /// </summary>
        public static string AmountForQuestion {
            get {
                return ResourceManager.GetString("AmountForQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string AppRole {
            get {
                return ResourceManager.GetString("AppRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi.
        /// </summary>
        public static string AppUser {
            get {
                return ResourceManager.GetString("AppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitabça.
        /// </summary>
        public static string Booklet {
            get {
                return ResourceManager.GetString("Booklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mətn adı.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıqlama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sualın bitmə nömrəsi.
        /// </summary>
        public static string EndQuestionNumber {
            get {
                return ResourceManager.GetString("EndQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmtahan.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş imtahan.
        /// </summary>
        public static string ExamId {
            get {
                return ResourceManager.GetString("ExamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmtahan parametri.
        /// </summary>
        public static string ExamParameter {
            get {
                return ResourceManager.GetString("ExamParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş imtahan parametri.
        /// </summary>
        public static string ExamParameterId {
            get {
                return ResourceManager.GetString("ExamParameterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmə tarixi.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinif.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş sinif.
        /// </summary>
        public static string GradeId {
            get {
                return ResourceManager.GetString("GradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qrup.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödənişsiz.
        /// </summary>
        public static string IsFree {
            get {
                return ResourceManager.GetString("IsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açar.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual mətni.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual sayı.
        /// </summary>
        public static string QuestionCount {
            get {
                return ResourceManager.GetString("QuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş sual.
        /// </summary>
        public static string QuestionId {
            get {
                return ResourceManager.GetString("QuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səviyyə qiyməti.
        /// </summary>
        public static string QuestionLevel {
            get {
                return ResourceManager.GetString("QuestionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş sual səviyyəsi.
        /// </summary>
        public static string QuestionLevelId {
            get {
                return ResourceManager.GetString("QuestionLevelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual səviyyəsi.
        /// </summary>
        public static string QuestionLevelName {
            get {
                return ResourceManager.GetString("QuestionLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual parametri.
        /// </summary>
        public static string QuestionParameter {
            get {
                return ResourceManager.GetString("QuestionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual tipi.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş sual tipi.
        /// </summary>
        public static string QuestionTypeId {
            get {
                return ResourceManager.GetString("QuestionTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavab.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual məzmunu.
        /// </summary>
        public static string ResponseContent {
            get {
                return ResourceManager.GetString("ResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavab sayı.
        /// </summary>
        public static string ResponseCount {
            get {
                return ResourceManager.GetString("ResponseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual başlığı.
        /// </summary>
        public static string ResponseTitle {
            get {
                return ResourceManager.GetString("ResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavab tipi.
        /// </summary>
        public static string ResponseType {
            get {
                return ResourceManager.GetString("ResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölmə.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş bölmə.
        /// </summary>
        public static string SectionId {
            get {
                return ResourceManager.GetString("SectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlanğıc tarixi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sualın başlama nömrəsi.
        /// </summary>
        public static string StartQuestionNumber {
            get {
                return ResourceManager.GetString("StartQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fənn.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fənn sayı.
        /// </summary>
        public static string SubjectCount {
            get {
                return ResourceManager.GetString("SubjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş fənn.
        /// </summary>
        public static string SubjectId {
            get {
                return ResourceManager.GetString("SubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fənn parametri.
        /// </summary>
        public static string SubjectParameter {
            get {
                return ResourceManager.GetString("SubjectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş fənn parametri.
        /// </summary>
        public static string SubjectParameterId {
            get {
                return ResourceManager.GetString("SubjectParameterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mətn.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlıq.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məzmun.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi tipi.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş variant.
        /// </summary>
        public static string VariantId {
            get {
                return ResourceManager.GetString("VariantId", resourceCulture);
            }
        }
    }
}
